version: "3"

networks:
  internal:
    external: false

services:
  app:
    image: 705111241922.dkr.ecr.eu-west-3.amazonaws.com/my-ecr:${CIRCLE_SHA1}
    environment:
      - DATABASE_HOST=db
    ports:
      - 80:4000
    depends_on:
      - db

  db:
    image: postgres:9.6
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
