version: "3"

networks:
  internal:
    external: false

services:
  app:
    image: wttj_fullstack:0.1.0
    build:
      context: .
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_HOST=db
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: postgres:9.6
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
